<?php
/**
 * EmailNotificationActionNodeRequestDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Podro TMS API Docs
 *
 * This is [Podro TMS's](https://podro.com/products/tms) documentation.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EmailNotificationActionNodeRequestDataTest Class Doc Comment
 *
 * @category    Class
 * @description EmailNotificationActionNodeRequestData
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EmailNotificationActionNodeRequestDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EmailNotificationActionNodeRequestData"
     */
    public function testEmailNotificationActionNodeRequestData()
    {
    }

    /**
     * Test attribute "email_variable_name"
     */
    public function testPropertyEmailVariableName()
    {
    }
}
